# This file is auto-generated by the script generate_translation_profile.py
# Do not edit this file manually

FORMS =	../../gui/dck_qchat.ui \
	../../gui/dlg_settings.ui

SOURCES =	../../constants.py \
	../../gui/dck_qchat.py \
	../../gui/dlg_settings.py \
	../../gui/gui_commons.py \
	../../gui/qchat_tree_widget_items.py \
	../../logic/qchat_api_client.py \
	../../logic/qchat_messages.py \
	../../logic/qchat_websocket.py \
	../../plugin_main.py \
	../../tasks/dizzy.py \
	../../toolbelt/commons.py \
	../../toolbelt/env_var_parser.py \
	../../toolbelt/exceptions.py \
	../../toolbelt/log_handler.py \
	../../toolbelt/network_manager.py \
	../../toolbelt/preferences.py

TRANSLATIONS = qchat_fr.ts qchat_de.ts qchat_es.ts
